# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The InvoiceKit Authors

from typing import Final

ENGINE_ABI_VERSION: Final[int]
__version__: str

class EngineResult:
    @property
    def status(self) -> int: ...
    @property
    def bytes(self) -> bytes: ...
    @property
    def len(self) -> int: ...
    def free(self) -> None: ...
    def __len__(self) -> int: ...

def engine_abi_version() -> int: ...
def engine_process_json(request_bytes: bytes) -> EngineResult: ...
def process_engine_abi_json(request_bytes: bytes) -> bytes: ...
def engine_result_status(result: EngineResult | None) -> int: ...
def engine_result_bytes(result: EngineResult | None) -> bytes: ...
def engine_result_len(result: EngineResult | None) -> int: ...
def engine_result_free(result: EngineResult | None) -> None: ...
