{{/*
  SPDX-License-Identifier: Apache-2.0
  Copyright 2026 The InvoiceKit Authors
*/}}
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "invoicekit.fullname" . }}-postgres
  labels:
    {{- include "invoicekit.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "invoicekit.selectorLabels" (merge (dict "component" "postgres") .) | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "invoicekit.fullname" . }}-postgres
  labels:
    {{- include "invoicekit.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "invoicekit.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "invoicekit.selectorLabels" (merge (dict "component" "postgres") .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "invoicekit.selectorLabels" (merge (dict "component" "postgres") .) | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ printf "%s:%s" .Values.postgres.image.repository .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.auth.existingSecret }}
                  key: password
          ports:
            - containerPort: 5432
              name: postgres
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgres.auth.username | quote }}, "-d", {{ .Values.postgres.auth.database | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- with .Values.postgres.storage.storageClassName }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
{{- end }}
