"""Unit tests for the InvoiceKit license-header gate."""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TOOL = REPO / "tools" / "license-header"
sys.path.insert(0, str(TOOL))
import check_headers  # noqa: E402


def _make_crate(tmp_path: Path, body: str, *, name: str = "demo") -> Path:
    """Create a minimal crates/<name>/src/lib.rs under tmp_path with `body`."""
    src = tmp_path / "crates" / name / "src"
    src.mkdir(parents=True, exist_ok=True)
    target = src / "lib.rs"
    target.write_text(body, encoding="utf-8")
    return target


def _canonical_header(year: int = 2026) -> str:
    return (
        "// SPDX-License-Identifier: Apache-2.0\n"
        f"// Copyright {year} The InvoiceKit Authors\n\n"
    )


def test_well_formed_header_passes(tmp_path: Path) -> None:
    _make_crate(tmp_path, _canonical_header() + "pub fn ok() {}\n")
    exit_code = check_headers.main(["--check", "--repo-root", str(tmp_path)])
    assert exit_code == 0


def test_missing_header_fails(tmp_path: Path) -> None:
    _make_crate(tmp_path, "pub fn missing() {}\n")
    exit_code = check_headers.main(["--check", "--repo-root", str(tmp_path)])
    assert exit_code == 1


def test_missing_copyright_line_fails(tmp_path: Path) -> None:
    _make_crate(
        tmp_path,
        "// SPDX-License-Identifier: Apache-2.0\n\npub fn missing_copyright() {}\n",
    )
    exit_code = check_headers.main(["--check", "--repo-root", str(tmp_path)])
    assert exit_code == 1


def test_wrong_spdx_id_fails(tmp_path: Path) -> None:
    _make_crate(
        tmp_path,
        "// SPDX-License-Identifier: MIT\n// Copyright 2026 The InvoiceKit Authors\n\n"
        "pub fn wrong() {}\n",
    )
    exit_code = check_headers.main(["--check", "--repo-root", str(tmp_path)])
    assert exit_code == 1


def test_fix_inserts_header(tmp_path: Path) -> None:
    target = _make_crate(tmp_path, "pub fn missing() {}\n")
    exit_code = check_headers.main(["--fix", "--repo-root", str(tmp_path)])
    assert exit_code == 0
    body = target.read_text(encoding="utf-8")
    assert body.startswith("// SPDX-License-Identifier: Apache-2.0\n")
    assert "// Copyright " in body
    assert "pub fn missing() {}\n" in body


def test_fix_is_idempotent(tmp_path: Path) -> None:
    target = _make_crate(tmp_path, "pub fn missing() {}\n")
    check_headers.main(["--fix", "--repo-root", str(tmp_path)])
    body_first = target.read_text(encoding="utf-8")
    check_headers.main(["--fix", "--repo-root", str(tmp_path)])
    body_second = target.read_text(encoding="utf-8")
    assert body_first == body_second


def test_generated_files_are_skipped(tmp_path: Path) -> None:
    body = "// @generated by some tool; do not edit\npub fn gen() {}\n"
    _make_crate(tmp_path, body, name="generated-crate")
    exit_code = check_headers.main(["--check", "--repo-root", str(tmp_path)])
    assert exit_code == 0
