// Generated by InvoiceKit template compiler. Do not edit generated Typst.
// Template: basic-invoice
#set document(
  title: "Basic invoice",
  author: "InvoiceKit",
  date: datetime(year: 2026, month: 1, day: 1),
)
#set page(width: 210mm, height: 297mm, margin: 18mm)
#set text(font: "Libertinus Serif", size: 10pt)

= Invoice *INV-2026-0001*

#grid(
  columns: (1fr, 1fr),
  [*Supplier*],
  [InvoiceKit Trust Toolkit GmbH],
  [*Customer*],
  [Deterministic Buyer Ltd],
  [*Issue date*],
  [2026-01-15],
  [*Due date*],
  [2026-02-14],
)

#line(length: 100%)

#table(
  columns: (1fr, 1fr, 1fr, 1fr),
  [*Description*],
  [*Qty*],
  [*Unit price*],
  [*Line total*],
  [Format correctness subscription],
  [1],
  [EUR 100.00],
  [EUR 100.00],
  [Evidence bundle verification],
  [2],
  [EUR 25.00],
  [EUR 50.00],
)

*Payable* EUR 178.50
