// Generated by InvoiceKit template compiler. Do not edit generated Typst.
// Template: credit-note
#set document(
  title: "Credit note",
  author: "InvoiceKit",
  date: datetime(year: 2026, month: 1, day: 1),
)
#set page(width: 210mm, height: 297mm, margin: 18mm)
#set text(font: "Libertinus Serif", size: 10pt)

= Credit note *CN-2026-0001*

Original customer: *Deterministic Buyer Ltd*

#table(
  columns: (1fr, 1fr),
  [*Reason*],
  [*Amount*],
  [Credit for cancelled verification run],
  [EUR -50.00],
)

*Credit total* EUR -59.50
