// Generated by InvoiceKit template compiler. Do not edit generated Typst.
// Template: factur-x-summary
#set document(
  title: "Factur-X summary",
  author: "InvoiceKit",
  date: datetime(year: 2026, month: 1, day: 1),
)
#set page(width: 210mm, height: 297mm, margin: 18mm)
#set text(font: "Libertinus Serif", size: 10pt)

= Factur-X summary

#grid(
  columns: (1fr, 1fr),
  [*Profile*],
  [EN 16931],
  [*Document*],
  [INV-2026-0001],
  [*Supplier VAT*],
  [DE123456789],
  [*Customer VAT*],
  [GB987654321],
)

#table(
  columns: (1fr, 1fr, 1fr, 1fr),
  [*VAT category*],
  [*Rate*],
  [*Taxable*],
  [*Tax*],
  [S],
  [19%],
  [EUR 150.00],
  [EUR 28.50],
)

Generated from the typed InvoiceKit template language.
