// Generated by InvoiceKit template compiler. Do not edit generated Typst.
// Template: payment-reminder
#set document(
  title: "Payment reminder",
  author: "InvoiceKit",
  date: datetime(year: 2026, month: 1, day: 1),
)
#set page(width: 210mm, height: 297mm, margin: 18mm)
#set text(font: "Libertinus Serif", size: 10pt)

= Payment reminder

Invoice *INV-2026-0001* remains open.

Customer: *Deterministic Buyer Ltd*

Due date: *2026-02-14*

*Outstanding amount* EUR 178.50

Payable within 30 days by bank transfer.
