// Generated by InvoiceKit template compiler. Do not edit generated Typst.
// Template: tax-breakdown
#set document(
  title: "Tax breakdown",
  author: "InvoiceKit",
  date: datetime(year: 2026, month: 1, day: 1),
)
#set page(width: 210mm, height: 297mm, margin: 18mm)
#set text(font: "Libertinus Serif", size: 10pt)

= Tax breakdown for *INV-2026-0001*

#table(
  columns: (1fr, 1fr, 1fr, 1fr),
  [*Category*],
  [*Rate*],
  [*Taxable amount*],
  [*Tax amount*],
  [S],
  [19%],
  [EUR 150.00],
  [EUR 28.50],
)

*Net* EUR 150.00

*Tax* EUR 28.50

*Payable* EUR 178.50
