// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The InvoiceKit Authors

export type CurrencyCode = string;
export type DocumentKind = "invoice" | "credit-note";

export interface MoneyAmount {
  readonly amount: string;
  readonly currency: CurrencyCode;
}

export interface PostalAddress {
  readonly street: string;
  readonly city: string;
  readonly country: string;
}

export interface Party {
  readonly legalName: string;
  readonly vatId: string;
  readonly address: PostalAddress;
}

export interface InvoiceLine {
  readonly description: string;
  readonly quantity: string;
  readonly unitPrice: MoneyAmount;
  readonly lineTotal: MoneyAmount;
}

export interface TaxSubtotal {
  readonly category: string;
  readonly rate: string;
  readonly taxableAmount: MoneyAmount;
  readonly taxAmount: MoneyAmount;
}

export interface InvoiceTotals {
  readonly net: MoneyAmount;
  readonly tax: MoneyAmount;
  readonly payable: MoneyAmount;
}

export interface CommercialDocumentTemplateData {
  readonly documentKind: DocumentKind;
  readonly documentNumber: string;
  readonly issueDate: string;
  readonly dueDate?: string;
  readonly supplier: Party;
  readonly customer: Party;
  readonly lines: readonly InvoiceLine[];
  readonly taxSubtotals: readonly TaxSubtotal[];
  readonly totals: InvoiceTotals;
  readonly paymentTerms?: string;
  readonly note?: string;
}

export interface TemplateMetadata {
  readonly name: string;
  readonly title?: string;
}

export interface InvoiceTemplate<TData extends object> {
  readonly metadata: TemplateMetadata;
  readonly render: (data: TData) => readonly BlockNode[];
}

export type InlineNode = TextNode | StrongNode;
export type BlockNode = HeadingNode | ParagraphNode | GridNode | TableNode | StackNode | RuleNode;

interface TextNode {
  readonly kind: "text";
  readonly value: string;
}

interface StrongNode {
  readonly kind: "strong";
  readonly value: string;
}

interface HeadingNode {
  readonly kind: "heading";
  readonly level: 1 | 2 | 3;
  readonly content: readonly InlineNode[];
}

interface ParagraphNode {
  readonly kind: "paragraph";
  readonly content: readonly InlineNode[];
}

interface GridNode {
  readonly kind: "grid";
  readonly columns: 2 | 3;
  readonly rows: readonly (readonly InlineNode[])[];
}

interface TableNode {
  readonly kind: "table";
  readonly headers: readonly string[];
  readonly rows: readonly (readonly string[])[];
}

interface StackNode {
  readonly kind: "stack";
  readonly children: readonly BlockNode[];
}

interface RuleNode {
  readonly kind: "rule";
}

export class TemplateCompileError extends Error {
  constructor(message: string) {
    super(`${message}. Hint: check the template builder arguments before compiling.`);
    this.name = "TemplateCompileError";
  }
}

export function defineTemplate<TData extends object>(
  metadata: TemplateMetadata,
  render: (data: TData) => readonly BlockNode[],
): InvoiceTemplate<TData> {
  if (metadata.name.trim() === "") {
    throw new TemplateCompileError("template name must not be blank");
  }

  return {
    metadata: metadata.title === undefined ? { name: metadata.name } : metadata,
    render,
  };
}

export function compileTemplate<TData extends object>(
  template: InvoiceTemplate<TData>,
  data: TData,
): string {
  const body = template.render(data).map(renderBlock).join("\n\n");
  const title = template.metadata.title ?? template.metadata.name;
  return [
    "// Generated by InvoiceKit template compiler. Do not edit generated Typst.",
    `// Template: ${escapeComment(template.metadata.name)}`,
    "#set document(",
    `  title: \"${escapeTypstString(title)}\",`,
    "  author: \"InvoiceKit\",",
    "  date: datetime(year: 2026, month: 1, day: 1),",
    ")",
    "#set page(width: 210mm, height: 297mm, margin: 18mm)",
    "#set text(font: \"Libertinus Serif\", size: 10pt)",
    "",
    body,
    "",
  ].join("\n");
}

export function text(value: string | number): InlineNode {
  return {
    kind: "text",
    value: String(value),
  };
}

export function strong(value: string | number): InlineNode {
  return {
    kind: "strong",
    value: String(value),
  };
}

export function heading(level: 1 | 2 | 3, ...content: readonly InlineNode[]): BlockNode {
  return {
    kind: "heading",
    level,
    content,
  };
}

export function paragraph(...content: readonly InlineNode[]): BlockNode {
  return {
    kind: "paragraph",
    content,
  };
}

export function rule(): BlockNode {
  return {
    kind: "rule",
  };
}

export function stack(...children: readonly BlockNode[]): BlockNode {
  return {
    kind: "stack",
    children,
  };
}

export function grid(columns: 2 | 3, rows: readonly (readonly InlineNode[])[]): BlockNode {
  if (rows.length === 0) {
    throw new TemplateCompileError("grid requires at least one row");
  }

  for (const row of rows) {
    if (row.length !== columns) {
      throw new TemplateCompileError(`grid row has ${row.length} cells but expected ${columns}`);
    }
  }

  return {
    kind: "grid",
    columns,
    rows,
  };
}

export function table(headers: readonly string[], rows: readonly (readonly string[])[]): BlockNode {
  if (headers.length === 0) {
    throw new TemplateCompileError("table requires at least one header");
  }

  for (const row of rows) {
    if (row.length !== headers.length) {
      throw new TemplateCompileError(
        `table row has ${row.length} cells but expected ${headers.length}`,
      );
    }
  }

  return {
    kind: "table",
    headers,
    rows,
  };
}

export function money(value: MoneyAmount): string {
  return `${value.currency} ${value.amount}`;
}

function renderBlock(node: BlockNode): string {
  if (node.kind === "heading") {
    return `${"=".repeat(node.level)} ${renderInlineSequence(node.content)}`;
  }

  if (node.kind === "paragraph") {
    return renderInlineSequence(node.content);
  }

  if (node.kind === "grid") {
    return renderGrid(node);
  }

  if (node.kind === "table") {
    return renderTable(node);
  }

  if (node.kind === "stack") {
    return node.children.map(renderBlock).join("\n\n");
  }

  if (node.kind === "rule") {
    return "#line(length: 100%)";
  }

  return assertNever(node);
}

function renderInline(node: InlineNode): string {
  if (node.kind === "text") {
    return escapeTypstText(node.value);
  }

  if (node.kind === "strong") {
    return `*${escapeTypstText(node.value)}*`;
  }

  return assertNever(node);
}

function assertNever(node: never): never {
  throw new TemplateCompileError(`unsupported template node: ${JSON.stringify(node)}`);
}

function renderInlineSequence(nodes: readonly InlineNode[]): string {
  return nodes.map(renderInline).join("");
}

function renderGrid(node: GridNode): string {
  const columns = Array.from({ length: node.columns }, () => "1fr").join(", ");
  const cells = node.rows
    .flatMap((row) => row.map((cell) => `[${renderInline(cell)}]`))
    .join(",\n  ");
  return `#grid(\n  columns: (${columns}),\n  ${cells},\n)`;
}

function renderTable(node: TableNode): string {
  const columns = Array.from({ length: node.headers.length }, () => "1fr").join(", ");
  const cells = [
    ...node.headers.map((header) => `[*${escapeTypstText(header)}*]`),
    ...node.rows.flatMap((row) => row.map((cell) => `[${escapeTypstText(cell)}]`)),
  ].join(",\n  ");
  return `#table(\n  columns: (${columns}),\n  ${cells},\n)`;
}

function escapeComment(value: string): string {
  return value.replaceAll("\n", " ").replaceAll("\r", " ");
}

function escapeTypstString(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
}

function escapeTypstText(value: string): string {
  return value
    .replaceAll("\\", "\\\\")
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]")
    .replaceAll("#", "\\#")
    .replaceAll("*", "\\*")
    .replaceAll("_", "\\_")
    .replaceAll("`", "\\`")
    .replaceAll("$", "\\$");
}
